# Change these first
owner: limenetwork # Your GitHub organization or username, where this repository lives
repo: limestatus # The name of this repository

sites:
  - name: Towny 1
    url: $SERVER_1
    port: $TPORT_1
    check: "tcp-ping"
    icon: https://craftlime.net/apps/main/public/assets/img/extras/header-logo.png
  - name: Towny 2
    url: $SERVER_1
    port: $TPORT_2
    check: "tcp-ping"
    icon: https://craftlime.net/apps/main/public/assets/img/extras/header-logo.png
  - name: Towny 3
    url: SERVER_1
    port: $TPORT_3
    check: "tcp-ping"
    icon: https://craftlime.net/apps/main/public/assets/img/extras/header-logo.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.craftlime.net
  # baseUrl: /your-repo-name
  logoUrl: https://craftlime.net/apps/main/public/assets/img/extras/header-logo.png
  name: LimeNetwork - Durum
  introTitle: "**LimeNetwork** CraftLime sunucu durum sayfası."
  introMessage: Minecraft sunucularımızın durumunu bu sayfadan öğrenebilirsiniz.
  theme: dark
  navbar:
    - title: Sunucu Durumu
      href: /
    - title: Ana Site
      href: https://craftlime.net
    - title: Haritalar
      href: http://map.craftlime.net

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
